fixed issue #4
OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium pull request #8
Opened 2019-08-27 11:42 UTC by tkoyama010

fixed issue #4

2019-08-29 12:45 UTC, inabower requested changes
すみません。Twitter IDの方は@public_inabowerでお願いできますでしょうか。

2019-08-30 00:06 UTC, tkoyama010 commented
修正しました。よろしくお願いいたします。

2019-08-30 13:14 UTC, inabower reviewed
確認しました。
遅くなりました。

2019-08-30 20:34 UTC, tkoyama010 commented
ありがとうございました。1人にレビュー頂いたのでマージします。

2019-08-30 20:34 UTC, merged